#version: '3.9'

services:
  db:
    image: postgres:18
    container_name: db
    restart: unless-stopped
    environment:
      POSTGRES_USER: admin_user
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: db1
    ports:
      - "5431:5432"
    volumes:
      - ~/backups/postgres_data:/var/lib/postgresql

    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U admin_user" ]
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api
    restart: unless-stopped
    expose:
      - 8100
    ports:
      - "8100:8100"
    environment:
      DB_HOST: db
      DB_NAME: db1
      DB_PASSWORD: postgres
      DB_PORT: 5432
      DB_USER: admin_user
      EMAIL_HOST: email
      EMAIL_PORT: 8200
      API_PORT: 8100
#      ENV: PROD
    depends_on:
      db:
        condition: service_healthy

  email:
    build:
      context: ../kontenerkiEmail
      dockerfile: Dockerfile
    container_name: email
    restart: unless-stopped
    expose:
      - 8200
    ports:
      - "8200:8200"
    environment:
      EMAIL_PASSWORD: litcviutipqwkxsw
      EMAIL_USER: parkingostrowskiego@gmail.com
      API_NAME: api
      API_PORT: 8100
      EMAIL_PORT: 8200
#      ENV: PROD
