version: '3.9'

services:
  db:
    image: postgres:17.5
    container_name: db
    restart: unless-stopped
    environment:
      POSTGRES_USER: admin_user
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: db1
    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api
    restart: unless-stopped
    ports:
      - "100:100"
    environment:
      DB_URL: jdbc:postgresql://db:5432/db1
      DB_USER: admin_user
      DB_PASSWORD: postgres
      EMAIL_NAME: email
      EMAIL_PORT: 200
    depends_on:
      - db

  email:
    build:
      context: ../email
      dockerfile: Dockerfile
    container_name: email
    restart: unless-stopped
    expose:
      - 200
    ports:
      - "200:200"
    environment:
      EMAIL_PASSWORD: litcviutipqwkxsw
      EMAIL_USER: parkingostrowskiego@gmail.com
      API_NAME: api
      API_PORT: 100
      ENV: DEV

volumes:
  postgres_data:
