version: '3.9'

services:
  db:
    image: postgres:latest
    container_name: db
    restart: unless-stopped
    environment:
      POSTGRES_USER: admin_user
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: db1
    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api
    ports:
      - "100:100"
    environment:
      DB_URL: jdbc:postgresql://db:5432/db1
      DB_USER: admin_user
      DB_PASSWORD: postgres
    depends_on:
      - db

volumes:
  postgres_data:
