ktor:
  application:
    modules:
      - com.kontenery.ApplicationKt.module
  deployment:
    port: "$API_PORT:8100"

#postgres:
#  url: "$DB_URL:jdbc:postgresql://localhost:5431/db1"
#  url: "$DB_URL:jdbc:postgresql://localhost:5430/db1"
#  user: "$DB_USER:postgres"
#  password: "$DB_PASSWORD:postgres"
#  driver: "org.postgresql.Driver"



