ktor:
  application:
    modules:
      - com.kontenery.ApplicationKt.module
  deployment:
    port: ${API_PORT:8100}

api:
  env: ${API_ENV:DEV}

  email:
    host: ${EMAIL_HOST:localhost}
    port: ${EMAIL_PORT:8200}

  db:
    host: ${DB_HOST:db}
    port: ${DB_PORT:5432}
    name: ${DB_NAME:db1}
    user: ${DB_USER:admin_user}
    password: ${DB_PASSWORD:postgres}

    auth:
      secretAuth: ${JWT_SECRET:secretAuth}
      secretRefresh: ${JWT_SECRET:secretRefresh}
      issuer: ${JWT_ISSUER:ktor sample app}
      audience: ${JWT_AUDIENCE:jwt-audience}
      realm: ${JWT_REALM:ktor sample app}
      validityMs: ${VALIDITY_MS:60000}
      googleClientId: ${GOOGLE_CLIENT_ID:1234567890}
      appSecret: ${APP_SECRET:}
      appLogin: ${APP_LOGIN:}
    

