name: Deploy to VPS

on:
  push:
    branches: [ "master" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout main repo
        uses: actions/checkout@v4

      - name: Checkout email repo
        uses: actions/checkout@v4
        with:
          repository: wilczynski87/kontenerkiEmail
          token: ${{ secrets.GH_PAT }}
          path: kontenerkiEmail

      - name: Configure SSH
        env:
          HOST: ${{ secrets.VPS_HOST }}
          USER: ${{ secrets.VPS_USER }}
          PORT: ${{ secrets.VPS_PORT }}
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.VPS_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

          cat <<EOF > ~/.ssh/config
          Host vps
            HostName $HOST
            User $USER
            Port $PORT
            IdentityFile ~/.ssh/id_rsa
            StrictHostKeyChecking no
          EOF

      - name: Upload both repos to VPS
        run: |
          rsync -az --delete --exclude '.git' --exclude '.github' ./ vps:/opt/app/
          rsync -az --delete ./kontenerkiEmail/ vps:/opt/kontenerkiEmail/
          
      - name: Build and deploy (zero downtime)
        run: |
          ssh vps "
            docker rm -f api email || true
            cd /opt/app
            docker compose pull
            docker compose build
            docker compose up -d --no-deps --build api
            docker compose up -d --no-deps --build email
          "
